### ISSUE TITLE
How may I install a client side lib in SSR mode ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [devCrossNet/vue-starter#105]
Hello, guys,

Just a quick question, I wonder how to implement a 3rd party wyswyg lib in your projet in SSR mode ? For example the 'vue-quill-editor' (https://github.com/surmon-china/vue-quill-editor) ? 

Appreciate your helps.

**Comment by devCrossNet** [comment]
hey @be-next-hotdog,

did you already try to implement it and did you get any errors?

**Comment by be-next-hotdog** [comment]
Indeed, I tried implementing in client or server entry script but always got 'Document is undefined' error.

**Comment by devCrossNet** [comment]
I'll have a look at it asap @be-next-hotdog

**Comment by devCrossNet** [comment]
hey @be-next-hotdog,

no, sorry I have to find some time. did you follow the guide in the readme of this lib? seems to be pretty detailed.

**Comment by be-next-hotdog** [comment]
To be honest, I tried many a times to implement this editor,  I did grasped the quill lib instance after the rendering but could not embed the target div tag. Therefore, I wonder what should I do exactly in your client side entry script before/during/after the rendering. I use at the beginning the `vue-ssr-starter-kit` but as I saw the client/server entries are the same.

**Comment by devCrossNet** [comment]
ok, I'll try to figure it out during the weekend

**Comment by devCrossNet** [comment]
@be-next-hotdog I created a branch with the implementation: https://github.com/devCrossNet/vue-starter/commit/39319793ba14898f85935bdddb59aede5914cf98

it was really easy to implement, I did just follow the instructions from the readme. Would be good if you could try it a little more next time before you create an issue.

Hope that helps, please close this issue if everything is ok 👍

**Comment by be-next-hotdog** [comment]
@devCrossNet So sorry, I admit that I made a stupid oversight, what I thought dist/ssr contains all the necessary elements after rendering, including style sheets.

My bad, Thx a lot anyway 👍
