### ISSUE TITLE
How to implement the 3rd party plugin without support SSR ?

### ISSUE THREAD

**Issue by be-next-hotdog** [devCrossNet/vue-starter#117]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

Hello,

WIP on integrating another 3rd party plugin without SSR support (https://github.com/zdy1988/vue-jstree) and really sorry to disturb you again. I'm looking forward to figuring out a solution (tuto or example) solving this kind of `3rd party plugin integration issue` once and for all. As someone indeed published a tuto to introduce how fix it in Nuxt (i.e. https://medium.com/@codebeast_/why-your-third-party-plugin-dont-work-in-nuxt-and-how-to-fix-it-d1a8caadf422)

Will be grateful for any tips and please let me know if we've documented somewhere yet.

## Versions.
```
browser:
browser version: 
operating system: 
```

**Comment by devCrossNet** [comment]
@be-next-hotdog can I close this issue?

**Comment by be-next-hotdog** [comment]
@devCrossNet sorry guy to reply you so late (was on vacations). I tested quickly your solution, but the re-render mechanism impacts slightly the rendering of several charts. Please tell me if you figure out a better solution, otherwise I'll redefine the page layout and move the tree viewer to a more independent work panel. 
So grateful to your tips anyway :)
