### ISSUE TITLE
Design System

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#133]
Provide a full-featured design system including sketch file to start new projects as fast as possible

**Comment by paolog22** [comment]
can we have a non-typescript variant for this build?

**Comment by devCrossNet** [comment]
Hey @paolog22,
I don't have the capacity to maintain two versions of this project and typescript is also one of the value propositions of the vue-starter because it is much more scalable and safe than vanilla javascript.

Give it a try 👍

**Comment by paolog22** [comment]
@devCrossNet this seems great.. sure my next project i will use this :) thank you

**Comment by mkirstetter** [comment]
How do you plan to do with the sketch thing? I'm currently at sketching on a new project

**Comment by devCrossNet** [comment]
@mkirstetter our design team is currently working on a design system. I don't know when it's finished but as soon as it is finished I will plan version 2 of the starter and implement the new design system.

**Comment by devCrossNet** [comment]
progress can be seen here: https://github.com/devCrossNet/vue-starter/tree/refactor/ui
