### ISSUE TITLE
Hot reloading for the Express server

### ISSUE THREAD

**Issue by Riari** [devCrossNet/vue-starter#134]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

## Desired functionality.
Hot reloading of server modules. I know the server is responsible for client and isomorphic building/HMR, so this might not be possible, but having to restart the entire stack to reflect a change in the Express code is painful.

**Comment by devCrossNet** [comment]
hey @Riari,

a really good request, I didn't think of this use case because I usually use external REST APIs. But this feature is essential if your backend lives in the express app.

can you try this solution: https://github.com/devCrossNet/vue-starter/commit/0472d36445b8c8180353aba2b19d990b97128c70
and give me feedback?

I'll merge it into master as soon as you approve it.

Regards

**Comment by Riari** [comment]
Hey,

I should have pointed out that I tried nodemon already and found it was too slow, since it restarts the entire process and that in turn triggers webpack building the client and isomorphic sources. I think there might be a way of doing it if the Express server and application are split into separate files and HMR then applied to the app.

The first part of this article looks like a promising method: https://hackernoon.com/hot-reload-all-the-things-ec0fed8ab0

**Comment by devCrossNet** [comment]
ok, will have a look at it 👍

**Comment by devCrossNet** [comment]
hey @Riari,

can you give this a test ride? https://github.com/devCrossNet/vue-starter/commit/34f102d8ae48d1c31cee3194522911a2598b1c38

I think it's much better and it also reloads the i18n files in dev.

**Comment by Riari** [comment]
That looks like it's almost working perfectly! But the server doesn't come up - I think that's because enabling watch mode in webpack means it never gets as far as running `node ./dist/server/server.js`. The article mentions [start-server-webpack-plugin](https://github.com/ericclemmons/start-server-webpack-plugin), which seems like it might be necessary in this case.

**Comment by devCrossNet** [comment]
I got it not working with typescript. can you try to increase the sleep in the dev script? that's a dirty hack, but just to get it running for testing.

**Comment by Riari** [comment]
OK, I tried increasing it to 8, but it simply never gets that far. I would expect to see some output from the server (starting with `info: server started at http://localhost:3000`), but there is none. Not sure how it's even working for you!

**Comment by devCrossNet** [comment]
I will have a look at it later 👍

**Comment by devCrossNet** [comment]
@Riari can you check out the `feat/dev-express` branch and help me to find a good solution?

I would really appreciate it :blush: 

you can use the code that I already have written to create a PR or just give me some hints on this issue.

thx in advance
