### ISSUE TITLE
component: data-grid/table

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#141]
a new component that can display data as a table and should include:

- display JSON as table
- sorting
- filtering
- pagination or endless scrolling
- custom cell renderer (optional for MVP)
- server-side-rendering

**Comment by 40818419** [comment]
we also will need:

1. cell rendering
```
{ name: 'start', type: 'date', dateFormat: 'n/j/Y' },
{ name: 'salary', type: 'float' },
{ name: 'active', type: 'bool' }
```
2. Edit cells
3. Pagination based on server request

What do you think?

**Comment by devCrossNet** [comment]
Let‘s create a new ticket for this 👍
