### ISSUE TITLE
Implement cache middleware

### ISSUE THREAD

**Issue by GustavoRPS** [devCrossNet/vue-starter#149]
[Results of PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fvue-starter.herokuapp.com%2F&tab=mobile)

To improve even more this repositorie is be nice implement an response caching middleware or use one like [kwhitley/apicache](https://github.com/kwhitley/apicache)

https://github.com/devCrossNet/vue-starter/blob/b2ae228a7d08f2b3b1d634da75b30f1975549be7/src/server/middlewares/index.ts#L1-L10

```
import * as Express      from 'express'; 
import * as bodyParser   from 'body-parser'; 
import * as cookieParser from 'cookie-parser'; 
import * as compression  from 'compression'; 
import * as apicache from 'apicache';
  
export const applyMiddlewares = (app: Express.Application) => { 
  app.use(bodyParser.json()); 
  app.use(cookieParser()); 
  app.use(compression({ threshold: 0 })); 
  app.use(apicache.middleware('48 hour'))
}; 
```

**Comment by GustavoRPS** [comment]
Good point!

[There is where they write](https://github.com/kwhitley/apicache/blob/5ed6c8e91a8835d9e3c345cbdfbd682a78ecf639/src/apicache.js#L166-L174) the `cache-control` key on the header.

For what I read the code they not modify the header only add `cache-control` key but the main propose of the lib if for REST API but I believe can work without other `Content-Type` to;

There is a [more simple implementation](https://glitch.com/edit/#!/server-side-cache-express);

```
const mcache = require('memory-cache');

var cache = (duration) => {
  return (req, res, next) => {
    let key = '__express__' + req.originalUrl || req.url
    let cachedBody = mcache.get(key)
    if (cachedBody) {
      res.send(cachedBody)
      return
    } else {
      res.sendResponse = res.send
      res.send = (body) => {
        mcache.put(key, body, duration * 1000);
        res.sendResponse(body)
      }
      next()
    }
  }
}
```

**Comment by devCrossNet** [comment]
did you have a look at this line: https://github.com/devCrossNet/vue-starter/blob/master/src/server/routes/SSRRoutes.ts#L16 ?

this is the cache for the rendered HTML, maybe this is already what you want.

**Comment by GustavoRPS** [comment]
That's partly what I'm after. But and the cache for `js`, `png`, etc?

Have you see the [tesults of PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fvue-starter.herokuapp.com%2F&tab=mobile)? To improve even more the score only need cache for `js` and `png` files.

**Comment by devCrossNet** [comment]
it would be good if they would recommend a cache time value in the docs. apparently, 24h is not enough for them.

What would you recommend?

**Comment by GustavoRPS** [comment]
Actually it was already done but the code is a bit scattered in my opinion. +1 to cache "middleware" in my opinion, would centralize the cache setting.

Let's try `4w`?

**Comment by devCrossNet** [comment]
I would be happy to change the code in a way that makes it more obvious (also it's not a thing people really care about or change often). If you have a recommendation, let me know 👍 

But I would not feel comfortable with replacing this one-liner with a new dependency, that's just too much.

anyway, I will change the cache time to 4/8 weeks and see if pagespeed recognizes it and I'll add it to version 1.1. 😊

**Comment by GustavoRPS** [comment]
If te 4/8 work for PageSpeed Insights you can close the issue with congratulations

**Comment by devCrossNet** [comment]
`4w` did the trick, will add it to version 1.1 and close this ticket 👍 

Thank you very much @GustavoRPS 😊 

<img width="647" alt="screen shot 2018-06-08 at 10 36 15" src="https://user-images.githubusercontent.com/1667598/41147881-d2e7aebc-6b07-11e8-9270-5f9c9a7a5f05.png">
