### ISSUE TITLE
Add navigation progress indicator

### ISSUE THREAD

**Issue by xMartin** [devCrossNet/vue-starter#184]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

## Desired functionality.

Add navigation progress indicator like https://github.com/hilongjw/vue-progressbar.

For routes that wait for data the UI can feel unresponsive as the browsers loading indicator does not work with client-side page transitions. Would be nice to have a solution integrated in the starter.

**Comment by devCrossNet** [comment]
do you want to try to implement it by yourself?

**Comment by xMartin** [comment]
Will try to get there as soon as I have my basic app running.

**Comment by xMartin** [comment]
See #186 for a discussion on how to best implement this.
