### ISSUE TITLE
component: maps

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#185]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

it would be interesting to have a map component e.g. a nice leaflet integration or something like that.

**Comment by SilverLeaves** [comment]
Do you mean Google map components and Baidu map components?

**Comment by devCrossNet** [comment]
I want to show how to use leaflet.js or something similar (but I think this is the most optimized map) in the vue-starter.

there are already vue-leaflet implementations but they create a lot of overhead. I am not quite sure if the idea will last because it's not such a common use-case

**Comment by SilverLeaves** [comment]
https://openlayers.org/

**Comment by devCrossNet** [comment]
@SilverLeaves open layers is a really huge library compared to leaflet. 
I already worked with several maps starting from google maps over open layers ending with leaflet. 
so from my experience leaflet is the lib that is most performant.

**Comment by devCrossNet** [comment]
This component is not common enough to add it to the starter.
