### ISSUE TITLE
A word problem —— localisation, I want to make sure that the word is "beast" or "best".

### ISSUE THREAD

**Issue by SilverLeaves** [devCrossNet/vue-starter#188]
## A word problem —— “*Beast* mode playlist on Youtube” in productivity tip of introduction.md
```
- [ ] localisation, I want to make sure that the word is "beast" or "best".
```

## Versions.
```
firefox:
lastest: 
windows10: 
```

## Repro steps.
```bash
vuepress dev docs
```
And then click  "get started" & scroll to productivity tip

## Desired functionality.
I'm working for localisation. I need a reasonable translation. I want to make sure that the word is "beast" or "best".

### Mention any other details that might be useful.
![default](https://user-images.githubusercontent.com/31165554/43114403-843e13a2-8f31-11e8-89dc-45338d7f4984.png)

**Comment by devCrossNet** [comment]
Heyyy 🙂

It is beast mode.

That means that you code like a beast - focused, fast and without any distractions 👍

**Comment by SilverLeaves** [comment]
Ok, 🙂!
