### ISSUE TITLE
Build SPA: "npm run build:spa" not work correctly & a long time for build

### ISSUE THREAD

**Issue by SilverLeaves** [devCrossNet/vue-starter#191]
## "npm run build:spa" not work correctly
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```

## Versions.
```
firefox:
lastest: 
windows10: 
corei5-8250U:
```

## Repro steps.
```bash
npm run build:spa
npm i -g anywhere
cd dist
anywhere
```

## Desired functionality.
* SPA without server-side
* A short time to clean up
* A short time to build

### Mention any other details that might be useful.

*  SPA always show error for me. Whatever language it is.

![The SPA not work correctly](https://user-images.githubusercontent.com/31165554/43196551-e4353af6-903a-11e8-96eb-bf891872fafb.png)

## A long time for build

* "npm run build:spa" tookes me more than 20min, 

then I add "build:span" without `run clean` to `package.json`,

* "npm run build:spa" tookes me 13min.

 enn...

![too long time to build](https://user-images.githubusercontent.com/31165554/43196556-ecefdfb6-903a-11e8-95a7-789bd4fd92e8.png)

**Comment by devCrossNet** [comment]
I think you translated something wrong in one of the i18n files. I'll fix that asap (https://github.com/devCrossNet/vue-starter/blob/master/i18n/en.json#L3)

the build on my machine takes 2 minutes. can you give me more information about your operating system etc.?

**Comment by SilverLeaves** [comment]
## hardware

![default](https://user-images.githubusercontent.com/31165554/43198304-c56f96ec-9040-11e8-8fcc-98e91275587f.png)
## hardware
![default](https://user-images.githubusercontent.com/31165554/43198361-f89ab5ce-9040-11e8-9056-900ea691265c.png)
## system lastest windows10
![default](https://user-images.githubusercontent.com/31165554/43198390-14490b9a-9041-11e8-895a-dadf557f1417.png)

**Comment by devCrossNet** [comment]
But should it not be `Chinese`?

In the English language, you see the English translation for Chinese.
In German, you see the German translation for Chinese, etc.?

Or is it common to display `中文` just in case the Chinese audience cannot read English at all?

**Comment by devCrossNet** [comment]
yes, you have to educate me a little bit 😊 

I never did something for the Chinese market.

**Comment by devCrossNet** [comment]
regarding the performance. I have the same issue on my DELL workstation with windows 10. I already reached out to the support, the NPM team and some people from Microsoft and the answer were more or less "it works on my machine".

I have no idea why Win is so slow sometimes. A normal `npm install` on my DELL workstation takes at least 10 minutes.

**Comment by SilverLeaves** [comment]
I think Microsoft is doing a good job. Very friendly，Very kindly.
![default](https://user-images.githubusercontent.com/31165554/43198731-3daae016-9042-11e8-90f2-db21ba8d8dd9.png)

**Comment by devCrossNet** [comment]
yes, it makes total sense now. I mean the only people who have to understand it are the people that are actually speaking the language.

That means we could get rid of the translations for the languages at all and hardcode them for every locale in the target language.

**Comment by SilverLeaves** [comment]
About `npm install` , in china ,it slowly too. 

but we have `cnpm`, a mirror of npm repertory. you can try [cnpm](https://npm.taobao.org/)

## install 
```bash
npm i -g cnpm
```
## use
```
cnpm install
```

**Comment by devCrossNet** [comment]
wow, this is impressive 👍

but back to your issue. I have no answer why it is so slow on windows and I will fix the translation issue in a few hours. maybe we can leave this open and see if we find a solution in the future.

**Comment by SilverLeaves** [comment]
> That means we could get rid of the translations for the languages at all and hardcode them for every locale in the target language.

On language selection, I didn't mean any offense. It's up to you.

**Comment by SilverLeaves** [comment]
In my issue, the best important thing is **SPA always show error for me. Whatever language it is.**

**Comment by devCrossNet** [comment]
I didn't understand it as an offense. I learned something from you, that's great!

I'll have a look at the SPA build later. how do you serve the SPA? with a locally installed web-server or something?

**Comment by SilverLeaves** [comment]
I use  `Object Storage Service (OSS)` to provide static resources. I paid 9RMB (about 1.33 dollar) for 40GB storage space with 1year. Data flow is 0.8RMB (about 0.12 dollar) for 1GB.

And I put my `SPA page` or `.html page` in OSS, then I get a webstation. like [this page](http://oss.saigao.fun/playground/tensorflowPlayrouund/index.html) or [this page -rustdocs](http://rustdoc.saigao.fun/)

If I need a server to provide data or other service, I'll setup a normal server or use Function Compute（a kind of Serverless platform）

**Comment by devCrossNet** [comment]
ok, I tested it out locally with a python HTTP server which serves the index.html and it works as expected.

Are you serving the index.html in the root of your domain or is it in a subdirectory? (something like `example.com/vue-starter` instead of `example.com`).

and can you provide the console output, there should be the error stack trace.

**Comment by SilverLeaves** [comment]
* Open "localhost:8000" then it auto jump to  "localhost:8000/error"

![截图](https://user-images.githubusercontent.com/31165554/43201757-f5181dc8-904b-11e8-8b80-504be4b75107.png)

Maybe I'm not good enough, so it doesn't show me normally. ๑乛◡乛๑

**Comment by SilverLeaves** [comment]
## Log from chrome

![default](https://user-images.githubusercontent.com/31165554/43202137-271b45e2-904d-11e8-951d-f5c61a0e4f16.png)

## Log from firefox

![default](https://user-images.githubusercontent.com/31165554/43202163-448b3f10-904d-11e8-8096-84be0f9907f9.png)

![default](https://user-images.githubusercontent.com/31165554/43202223-7d7c35f4-904d-11e8-83c7-b7e396f69bd8.png)

**Comment by devCrossNet** [comment]
ahh, yes I see. ok, this has to be fixed. I will include the fix with the changes later. I'll write you as soon as I deploy it, then you can update your copy 👍

**Comment by SilverLeaves** [comment]
> I never did something for the Chinese market.

Creator of vuejs is Chinese & then vuejs in china is very popular.

So ... ennn ... maybe ... I guess ... exactly ... I think ... actually ..

**Now, vue-starter is something what you're doing for the Chinese market.**

**Comment by devCrossNet** [comment]
@SilverLeaves I fixed the issue, it was a simple fix: https://github.com/devCrossNet/vue-starter/commit/ec14fa065488b3e98c71465594cc26d34c9e438b

I also updated the i18n language stuff as discussed, makes much more sense now. Thanks for your input.

if you want to get the updated run `npm run update`
