### ISSUE TITLE
Don't change route in 404 or error

### ISSUE THREAD

**Issue by xMartin** [devCrossNet/vue-starter#193]
## Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

## Desired functionality.

When requesting a route that does not exist or that throws an error when rendering, the client-side code changes the routes to either `/not-found` or `/error` to render the respective error page. It would be better to render this content without changing the route just as it is done server-side.

**Comment by xMartin** [comment]
Test case to be implemented:
```diff
diff --git a/cypress/integration/404.spec.ts b/cypress/integration/404.spec.ts
index b1928c9..6aeede2 100644
--- a/cypress/integration/404.spec.ts
+++ b/cypress/integration/404.spec.ts
@@ -1,7 +1,8 @@
 describe('404', () => {
 
-  it('should return display not-found page', () => {
+  it('should display not-found page', () => {
     cy.visit('http://localhost:3000/test', { failOnStatusCode: false });
+    cy.location('pathname').should('eq', '/test');
     cy.title().should('include', 'page not found');
   });
 ```
(Unfortunately Cypress doesn't support assertion of HTTP status codes.)

**Comment by devCrossNet** [comment]
```

**Comment by xMartin** [comment]
Great! I can use it for the redirect stuff, too.

**Comment by devCrossNet** [comment]
@xMartin now I know why I implemented the client side redirect.

If you render the error page on the server and the client side app takes over, it can not find the route and renders nothing instead.

I don't know how to prevent the re-rendering in the client.

**Comment by xMartin** [comment]
Yes, I know it's a tricky one. Needs to be implemented outside of standard routing.

**Comment by devCrossNet** [comment]
I don't want to hack it somehow. maybe we come back to this later 👍

**Comment by xMartin** [comment]
Unfortunately I wrote "404 or error". I'm still working on the error part, it's tricky. I'd leave it open a bit longer if you don't mind. Otherwise we can open a new issue for the error (500) case, adjust the title of this one and close it.

**Comment by devCrossNet** [comment]
Let’s leave it open 👍

**Comment by devCrossNet** [comment]
I will close this now. we can open another ticket if it pops up
