### ISSUE TITLE
chat || discussion: vue-cli 3 is coming, chat || discuss something?

### ISSUE THREAD

**Issue by SilverLeaves** [devCrossNet/vue-starter#198]
## chat || discussion

> * @vue/cli-ui is a built-in package of vue-cli which opens a full-blown UI.
Vue-cli 3.x is a complete rewrite, with a lot of new awesome features. You will be to select features like routing, Vuex or Typescript, then add and upgrade building blocks called "vue-cli plugins". But having so much more options also means the tool is now more complex and harder to start using. That's why we thought having a full-blown GUI would help discover the new features, search and install vue-cli plugins and unlock more possibilities overall while not being limited by a terminal interface. To sum up, vue-cli will not only allow you to bootstrap a new project easily, but it will also remain useful for ongoing work afterwards!

![1532621103 1](https://user-images.githubusercontent.com/31165554/43274099-c16cd956-9130-11e8-99ce-ab7a657a291c.jpg)

**Comment by devCrossNet** [comment]
You might wanna join our slack channel https://slack-vue-starter.herokuapp.com ?
