### ISSUE TITLE
docs: add a recommended architecture page

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#211]
I often see people that want to use vue or the vue-starter together with a PHP backend which makes no sense. We should add a recommendation on how the architecture should look like in order to use the vue-starter (and put some nice diagrams on it).

**Comment by SilverLeaves** [comment]
This is a small problem, but behind it is a big problem. This is the tip of the iceberg.

Tools do not solve the problem of programmer's knowledge. Tools can only reduce the difficulty of their use, but the ease of use of tools is positively related to complexity.

A man can't spin and weave at the same time. Of course, maybe you can, but it will be not easy to do.

Easy to use and easy to learn, which one is what you want?
