### ISSUE TITLE
dockerfile not working + missing docs

### ISSUE THREAD

**Issue by stavros-liaskos** [devCrossNet/vue-starter#214]
**Describe the bug**
Docker build is failing and docker is lacking documentation

**To Reproduce**
1. `docker build .`
2. See error

**Expected behavior**
Successfully built docker image

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
I made the fix. Submitting PR asap

**Comment by stavros-liaskos** [comment]
Hmmm.. A bit out of the scope of this ticket but I'm stuck at line:78 of [Contributing docs](https://github.com/devCrossNet/vue-starter/edit/master/.github/CONTRIBUTING.md). 
I throws:
```bash
remote: Permission to devCrossNet/vue-starter.git denied to stavros-liaskos.
fatal: unable to access 'https://github.com/devCrossNet/vue-starter.git/': The requested URL returned error: 403
```
Am I even allowed to push a new branch?

**Comment by devCrossNet** [comment]
@stavros-liaskos hey, you have to fork the repository to your github account and create a PR from your branch to the next branch in this repo 👍 

Thank you very much 😊
