### ISSUE TITLE
Using the store in `router.beforeEach()` breaks VueNavBar component Storybook

### ISSUE THREAD

**Issue by petronius** [devCrossNet/vue-starter#216]
**Describe the bug**

Because the global `CLIENT` is undefined in `store.ts`, if the store gets imported indirectly by a story in Storybook, it will break Storybook with a rather cryptic error. I assume this is because Storybook is setting the `"use strict"` pragma somewhere.

The error looks like this:
```
index.js:16 ReferenceError: CLIENT is not defined
    at Module../src/app/store.ts (store.ts:12)
    at __webpack_require__ (bootstrap:764)
    at fn (bootstrap:127)
    at Module.<anonymous> (router.ts:1)
    at Module../src/app/router.ts (router.ts:47)
    at __webpack_require__ (bootstrap:764)
    at fn (bootstrap:127)
    at Module.<anonymous> (VueNavBar.stories.ts:1)
    at Module../src/app/shared/components/VueNavBar/VueNavBar.stories.ts (VueNavBar.stories.ts:14)
    at __webpack_require__ (bootstrap:764)
```

In my case, this was because the `VueNavBar.stories.ts` imports the router, which in turn was importing `store.ts` (to make use of a getter).

Fixing this means that adding authentication right after setting up the starter won't immediately break Storybook.

**To Reproduce**
Steps to reproduce the behavior (from a fresh install of `vue-starter`):
1. In `router.ts` make use of the story in any way, for example, by adding this line to the `router.beforeEach()` function:
```diff
router.beforeEach((to: Route, from: Route, next: any) => {
+  var mycount = store.getters.counter;
   if (to.matched.some((record: RouteRecord) => record.meta.requiresAuth)) {
```
2. Run `npm run storybook`
3. Open `http://localhost:6006/`

**Expected behavior**

Setting up navigation guards that use store getters to check state should not cause Storybook to break.

**Screenshots**
<img width="1070" alt="screen shot 2018-08-29 at 15 06 03" src="https://user-images.githubusercontent.com/688429/44789619-52abb500-ab9d-11e8-8c9e-e3c9bd79f330.png">

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68

**Smartphone (please complete the following information):**
Not tested

**Additional context**

**Comment by devCrossNet** [comment]
I wouldn't suggest accessing the store inside a shared component. That is against the concept of having decoupled, reusable components.

Try to always pass down this values as a `prop` 👍

**Comment by petronius** [comment]
In this case, the component isn't accessing the store, but the story is importing the router (in order to pass it to the component), which in turn imports the store.

Is there a better way to reference the store in the router, without importing it directly?

**Comment by devCrossNet** [comment]
ok, I understand. I'll try to come up with a solution 👍

**Comment by devCrossNet** [comment]
I found a way to mock the router for storybook: https://github.com/devCrossNet/vue-starter/pull/234/files#diff-67a42cc74b668d1e7710029c548f276c

I'll try to reproduce your example and mock the router, if this works I'll close this issue.

**Comment by devCrossNet** [comment]
The mocking of the router in stories solves this issue.
