### ISSUE TITLE
Using i18n in shared components breaks Storybook

### ISSUE THREAD

**Issue by petronius** [devCrossNet/vue-starter#218]
**Describe the bug**
Using i18n with `$t()` in a shared component will throw an error in Storybook:
```
index.js:16 TypeError: Cannot read property '_t' of undefined
    at Proxy.Vue.$t (vue-i18n.esm.js:179)
    at Proxy.render (VueNavBar.vue?c4cd:13)
    at VueComponent.Vue._render (vue.esm.js:4544)
    at VueComponent.updateComponent (vue.esm.js:2788)
    at Watcher.get (vue.esm.js:3142)
    at new Watcher (vue.esm.js:3131)
    at mountComponent (vue.esm.js:2795)
    at VueComponent../node_modules/vue/dist/vue.esm.js.Vue.$mount (vue.esm.js:8540)
    at VueComponent../node_modules/vue/dist/vue.esm.js.Vue.$mount (vue.esm.js:10939)
    at init (vue.esm.js:4137)
```

**To Reproduce**
Steps to reproduce the behavior (on a fresh setup of `vue-starter`):
1. Add the following to a shared component (for example, `VueNavBar`):
```diff
       <div :class="$style.accent" />
     </div>

+    {{ $t('Component.test' /* testing */ ) }}
+
     <vue-grid>
       <vue-grid-row>
         <vue-grid-item fill>
```
2. Run `npm run storybook`
3. Select the component in Storybook

**Expected behavior**
Showing the default i18n text, since `Vue.use(VueI18n)` is already included in the `./storybook/config.js`.

**Screenshots**
<img width="1066" alt="screen shot 2018-08-29 at 15 58 44" src="https://user-images.githubusercontent.com/688429/44792607-8d651b80-aba4-11e8-9675-94f9adbe6a68.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version [e.g. 22]: 68

**Smartphone (please complete the following information):**
Not tested

**Additional context**

**Comment by petronius** [comment]
This looks related to https://github.com/storybooks/storybook/issues/1573

So you can actually avoid this error by adding the following to a component that uses i18n:
```diff
story.add('Default', () => ({
   router,
   components: { VueNavBar },
   template:   `<vue-nav-bar />`,
+  i18n: new VueI18n({}),
 }));
```

But maybe there is a way to do this automatically, with the current translation strings loaded, for all stories that Storybook loads?

**Comment by devCrossNet** [comment]
have a look at the storybook from the VueCalendar: https://github.com/devCrossNet/vue-starter/blob/master/src/app/shared/components/VueCalendar/VueCalendar.stories.ts#L13

this should solve the problem 😊

**Comment by petronius** [comment]
Much cleaner, thanks! Closing this as a case of "bad error messages generated by dependencies" 😀
