### ISSUE TITLE
ESLint

### ISSUE THREAD

**Issue by stavros-liaskos** [devCrossNet/vue-starter#219]
**Is your feature request related to a problem? Please describe.**
Lack of ESLint allows devs to write vague code syntax and conventions

**Describe the solution you'd like**
- I've worked before with [Nuxt's](https://github.com/nuxt/nuxt.js) eslint config and I suggest to integrate that as a solution
- Beautify and ESLint should not conflict each other
- (optional) git hooks for ESLinting on precommit?
- (optional) if so, create target config and fix all(?) `.vue` files

**Describe alternatives you've considered**
Nuxt's eslint config is quite similar to [https://standardjs.com/](https://standardjs.com/). I wouldn't suggest anything less than that

**Additional context**
I've already integrated ESLint in a fork. Let me know if I should proceed with a PR

**Comment by stavros-liaskos** [comment]
@devCrossNet It doesn't lint the `.vue` files while typing though nor on precommit. It lints only `.ts` files and runs the tests. Am I right? TBH, I am not familiar with TSLint.

**Comment by devCrossNet** [comment]
@stavros-liaskos then let's try to get TSLint working with .vue files. I'll do some research if I have some time

**Comment by stavros-liaskos** [comment]
I see what you mean now. Although eslint was doing great I stumbled upon the problem of not being able to read the lang=ts. Which means I can’t exlude files based on that and of course eslint throws errors on some typescript specific commands. That takes eslint out of the table then.
I’m switching to tslint and I will focus on optimising that. Unfortunately, currently I don’t have linting while typing. Let me know if that works for you. Precommit linting works as expected. I am also currently trying to use the standard lint config because I find the recommended one too “soft”

**Comment by devCrossNet** [comment]
tweak everything that it fits your project, this is exactly why I made the starter. everything you want to change is changeable - nothing is hidden or can't be changed.

I'll have a look at linting the .vue files asap. I am a little bit busy right now with my job. I will share my progress in this thread but it can take some time 👍

**Comment by stavros-liaskos** [comment]
I am afraid editor support for TSLint is [not possible](https://github.com/palantir/tslint/issues/2099) at the moment. Even when initializing a project with vue-cli v3: `vue create hello-world` and choosing typescript linter,  editor still ignores the rules.    
Note that I am using PhpStorm and that is still an [open issue](https://youtrack.jetbrains.com/issue/WEB-31044).

**Comment by devCrossNet** [comment]
good to know. but I think it would still be good to have the `npm run lint` task working with .vue components.

**Comment by stavros-liaskos** [comment]
I implemented ESLint, TSLint and Stylelint with the following configuration:
`package.json`:
```json
"scripts": {
    "lint": "concurrently \"npm run lint:ts\" \"npm run lint:es\"",
    "lint:ts": "tslint --fix -c tslint.json './src/**/*.ts' './tools/**/*.ts'",
    "lint:es": "eslint --fix --ext .js,.vue --ignore-path .gitignore --ignore-path .eslintignore $(find src/app/* -name '*.vue')",
    "lint:css": "stylelint --fix '**/*.vue'",
}
"devDependencies": {
    "@babel/traverse": "^7.0.0-beta.52",
    "babel-eslint": "^9.0.0",
    "eslint": "^5.4.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-loader": "^2.1.0",
    "eslint-plugin-html": "^4.0.5",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^7.0.1",
    "eslint-plugin-promise": "^4.0.0",
    "eslint-plugin-standard": "^4.0.0",
    "stylelint": "^9.5.0",
    "stylelint-config-standard": "^18.2.0",
    "stylelint-processor-html": "^1.0.0",
    "stylelint-scss": "^3.3.0",
}
```
`tslint.json`:
```json
{
  "extends": "tslint-config-standard",
  // add your custom rules here
  "rules": {
    "space-before-function-paren": [true, {"anonymous": "never", "named": "never", "asyncArrow": "never"}],
    "semicolon": [true, "always"],
    "one-var": ["error", "always"],
    "object-curly-spacing": ["error", "never", {"arraysInObjects": true, "objectsInObjects": true}]
  }
}
```
`.eslintrc.js`:
```js
{
  "extends": "tslint-config-standard",
  // add your custom rules here
  "rules": {
    "space-before-function-paren": [true, {"anonymous": "never", "named": "never", "asyncArrow": "never"}],
    "semicolon": [true, "always"],
    "one-var": ["error", "always"],
    "object-curly-spacing": ["error", "never", {"arraysInObjects": true, "objectsInObjects": true}]
  }
}
```
`.stylelintrc`:
```json
{
  "plugins": [
    "stylelint-scss"
  ],
  "extends": "stylelint-config-standard",
  "rules": {
    "no-empty-source": null
  }
}
```
There are 2 downsides:
1. It requires to edit dozens of files since `--fix` doesn't work for every single rule
2. `.vue` file with `lang=ts` must be added to a `.eslintignore` since there are cases that typescript throws syntax errors when linted with ESLint

However, the benefits are great since you have linters for everything.

I can open a PR since I implemented that already but I chose to not bind `lint:css` to `precommit` because I was bored of fixing all the errors.. At least you get an error in the IDE!

**Comment by devCrossNet** [comment]
I close this issue since the new vue-starter version has linting in vue-files for dev-mode.
