### ISSUE TITLE
Question: What is the difference between “starter” and "begainner"?

### ISSUE THREAD

**Issue by SilverLeaves** [devCrossNet/vue-starter#223]
I am sorry to ask this question. Because I couldn't find a reasonable explanation on the Internet. 

I'm a little confused about these two words.

eg: 
I'm a kid, I'm starting to learn "vue-starter".
Question: Starter or begainner, which I'm?

I'm Engineer, I'm starting to use "vue-starter".
Question: Starter or begainner, which "vue-starter" is?

(╥╯^╰╥)

**Comment by devCrossNet** [comment]
do you mean "beginner"? can't find the word "begainer" in a dictionary 😊

**Comment by SilverLeaves** [comment]
@devCrossNet Yeah, you're right.

**Comment by devCrossNet** [comment]
beginner is related to a `person` that just starts to learn something and starter is related to a `thing` to get started

for example, if you have a menu in a restaurant and you order a starter - that means you have something small to eat before you eat the main dish.

translated to tech - a starter/kitchen sink/boilerplate is something you can take and build on top of it

**Comment by SilverLeaves** [comment]
I'm a kid, I'm starting to learn "vue-starter".
Question: Starter or begainner, which I'm?
My answer：“beginner”

I'm Engineer, I'm starting to use "vue-starter"
Question: Starter or begainner, which "vue-starter" is?
My answer：“Starter”

Right？

**Comment by devCrossNet** [comment]
it's two different things. if you start using vue you are a beginner and use the vue-starter. if you are an advanced engineer you're using the vue-starter but you're not a beginner anymore.

**Comment by SilverLeaves** [comment]
@devCrossNet Thank you for your answer.😊
