### ISSUE TITLE
typing for prefetch message should be a promise

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#241]
add return type for prefetch function

**Comment by jmcdo29** [comment]
I'd love to help out with this. You may need to point me to where the prefetch function is though

**Comment by devCrossNet** [comment]
hey @jmcdo29 
here is the line of code: https://github.com/devCrossNet/vue-starter/blob/master/src/vue.plugins.d.ts#L14

**Comment by jmcdo29** [comment]
I've currently set it to Promise<any>. Is there a specific return type the promise should have?

**Comment by devCrossNet** [comment]
`any` type is ok, that’s what most of the libraries use in that case. Generics would be an Overkill at this Point.

Von: Jay McDoniel
Gesendet: Dienstag, 2. Oktober 2018 18:14
An: devCrossNet/vue-starter
Cc: Johannes Werner; Author
Betreff: Re: [devCrossNet/vue-starter] typing for prefetch message should be apromise (#241)

I've currently set it to Promise. Is there a specific return type the promise should have?
