### ISSUE TITLE
NPM RUN DEV Doesnt Progress , It just stays stagnate

### ISSUE THREAD

**Issue by CryptoRootz** [devCrossNet/vue-starter#285]
**Describe the bug**
So i clone the vue start repo, then i did npm install , the i did npm run dev and it just doesnt progress.... it pretty much stay stagnate..... 
**To Reproduce**

**Expected behavior**

**Screenshots**
> vue-starter@1.4.0 dev:server C:\Users\Dready\Desktop\PWA Vue WEB\vue-starter
> cross-env NODE_ENV=development webpack --mode development --config ./config/webpack.server.config.js

Starting type checking and linting service...
Using 1 worker with 2048MB memory limit

webpack is watching the files…

Debugger listening on ws://127.0.0.1:9230/c2b63751-6b10-4a61-83fc-a3d278763cbf
For help see https://nodejs.org/en/docs/inspector
Type checking and linting in progress...
Hash: ee784836c7f51c14e1c1
Version: webpack 4.22.0
Time: 11828ms
Built at: 2018-11-02 11:21:45
                        Asset       Size  Chunks             Chunk Names
   ../app/config/default.json  117 bytes          [emitted]
../app/config/production.json   75 bytes          [emitted]
          ../static/README.md  162 bytes          [emitted]
  ../static/browserconfig.xml  229 bytes          [emitted]
   ../static/icon-128x128.png   6.11 KiB          [emitted]
   ../static/icon-144x144.png   7.03 KiB          [emitted]
   ../static/icon-152x152.png   7.64 KiB          [emitted]
   ../static/icon-192x192.png   10.3 KiB          [emitted]
   ../static/icon-384x384.png   6.46 KiB          [emitted]
   ../static/icon-512x512.png   6.46 KiB          [emitted]
     ../static/icon-72x72.png   3.25 KiB          [emitted]
     ../static/icon-96x96.png   4.41 KiB          [emitted]
           ../static/logo.png   1.98 KiB          [emitted]
      ../static/manifest.json   1.06 KiB          [emitted]
         ../static/robots.txt   15 bytes          [emitted]
        ../static/sitemap.xml    0 bytes          [emitted]
                    server.js    101 KiB    main  [emitted]  main
Entrypoint main = server.js
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {main} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.11 KiB {main} [built]
[./node_modules/webpack/hot/poll.js?1000] (webpack)/hot/poll.js?1000 1.15 KiB {main} [built]
[./src/server/index.ts] 504 bytes {main} [built]
[./src/server/middlewares/index.ts] 297 bytes {main} [built]
[./src/server/routes/CounterRoutes.ts] 517 bytes {main} [built]
[./src/server/routes/DemoRoutes.ts] 608 bytes {main} [built]
[./src/server/routes/SSRRoutes.ts] 3.74 KiB {main} [built]
[./src/server/routes/StaticRoutes.ts] 710 bytes {main} [built]
[./src/server/server.ts] 640 bytes {main} [built]
[./src/server/utils/Logger.ts] 893 bytes {main} [built]
[express] external "express" 42 bytes {main} [built]
[http] external "http" 42 bytes {main} [built]
[winston] external "winston" 42 bytes {main} [built]
[0] multi ./src/server/index webpack/hot/poll?1000 40 bytes {main} [built]
    + 13 hidden modules
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:6380) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
info: server started at http://localhost:3000
No type errors found
No lint errors found
Version: typescript 3.1.3, tslint 5.11.0
Time: 44385ms
No type errors found
No lint errors found
Version: typescript 3.1.3, tslint 5.11.0
Time: 108644ms
No type errors found
No lint errors found
Version: typescript 3.1.3, tslint 5.11.0
Time: 108644ms
webpack built 8f9227f39cdbd761c04e in 168604ms
‼ ｢wdm｣: Hash: 8f9227f39cdbd761c04e
Version: webpack 4.22.0
Time: 168604ms
Built at: 2018-11-02 11:25:03
                                                        Asset      Size              Chunks                    Chunk Names
                components.components.6eece166fe1cf3ee7a79.js  1.74 MiB          components  [emitted]  [big]  components
components~counter.components~counter.e8593d57f5e67b3dfa46.js   102 KiB  components~counter  [emitted]         components~counter
      components~home.components~home.d25c920c617c50347ec9.js  75.5 KiB     components~home  [emitted]         components~home
                      counter.counter.34b83c15eae5c00062e0.js    44 KiB             counter  [emitted]         counter
                          error.error.412888abdd35f31fd0f0.js  38.3 KiB               error  [emitted]         error
                            home.home.9c33b626faab518a8524.js   587 KiB                home  [emitted]  [big]  home
                                                   index.html  1.79 KiB                      [emitted]
                            main.main.120517b96b4ef34af15d.js   892 KiB                main  [emitted]  [big]  main
                    notFound.notFound.a0b8d7b8755a675760c0.js  38.9 KiB            notFound  [emitted]         notFound
                                                   runtime.js  34.1 KiB             runtime  [emitted]         runtime
                        vendor.vendor.e289651a7fa8ee967a47.js  2.06 MiB              vendor  [emitted]  [big]  vendor
Entrypoint main [big] = runtime.js vendor.vendor.e289651a7fa8ee967a47.js main.main.120517b96b4ef34af15d.js
[./node_modules/ansi-html/index.js] 4.16 KiB {vendor} [built]
[./node_modules/ansi-regex/index.js] 135 bytes {vendor} [built]
[./node_modules/axios/index.js] 40 bytes {vendor} [built]
[./node_modules/html-entities/index.js] 231 bytes {vendor} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {vendor} [built]
[./node_modules/timers-browserify/main.js] 1.97 KiB {vendor} [built]
[./node_modules/vue/dist/vue.runtime.esm.js] 207 KiB {vendor} [built]
[./node_modules/webpack-hot-middleware/client-overlay.js] (webpack)-hot-middleware/client-overlay.js 2.16 KiB {vendor} [built]
[./node_modules/webpack-hot-middleware/client.js] (webpack)-hot-middleware/client.js 7.59 KiB {vendor} [built]
[./node_modules/webpack-hot-middleware/process-update.js] (webpack)-hot-middleware/process-update.js 4.26 KiB {vendor} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendor} [built]
[0] multi webpack-hot-middleware/client ./src/client/index 40 bytes {main} [built]
[./src/app/app.ts] 692 bytes {main} [built]
[./src/app/shared/services/HttpService.ts] 1.91 KiB {main} [built]
[./src/client/index.ts] 2.12 KiB {main} [built]
    + 655 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (261 KiB).
This can impact web performance.
Assets:
  components.components.6eece166fe1cf3ee7a79.js (1.74 MiB)
  home.home.9c33b626faab518a8524.js (587 KiB)
  main.main.120517b96b4ef34af15d.js (892 KiB)
  vendor.vendor.e289651a7fa8ee967a47.js (2.06 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (311 KiB). This can impact web performance.
Entrypoints:
  main (2.96 MiB)
      runtime.js
      vendor.vendor.e289651a7fa8ee967a47.js
      main.main.120517b96b4ef34af15d.js

Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.41 MiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.template.html] 1.79 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
i ｢wdm｣: Compiled with warnings.

(then i just stay here and doesnt move forward for hours)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devCrossNet** [comment]
Hey, I can’t see any issues in first sight. If you open http://localhost:3000 does it work or do you get any errors?

**Comment by devCrossNet** [comment]
@CryptoRootz any news on this?

**Comment by devCrossNet** [comment]
I close this issue because of inactivity
