### ISSUE TITLE
SPA build doesn't contain configs

### ISSUE THREAD

**Issue by devzsolt** [devCrossNet/vue-starter#294]
**Describe the bug**
The bundle produced by `npm run build:spa` doesn't contain app configs.

**To Reproduce**
1. set `"disableParticles": true` in the `default.json` config
2. `npm run dev` --> particles are not displayed as the config tells
3. `npm run build:spa` & serve locally --> particles are still rendered, the config was ignored

**Expected behavior**
Config should be available therefore [this hack](https://github.com/devCrossNet/vue-starter/commit/ec14fa065488b3e98c71465594cc26d34c9e438b) should be unnecessary.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox and Chrome as well

**Additional context**
I tried to add and use new configs and they work well in dev mode but just like the `disableParticles` config they aren't available in the SPA bundle.

Related issue: #191

**Comment by devCrossNet** [comment]
Hey @devzsolt,

I am not sure if we can integrate this feature with the SPA build. The purpose of the config is that you can transfer information from the server-environment to the application environment and in the SPA build you don't have a server. For that, we would have to come up with a client-side only solution and I don't know how this would fit together with the overall architecture.

I will add a hint in the docs for every feature if it is available in the SPA build or not. Or maybe get completely rid of the SPA build. I am not sure yet.

If you have an idea how to integrate it I would love to see a proposal.

Have a nice day 😊

**Comment by devzsolt** [comment]
Hey @devCrossNet I wanted to believe that your starter kit could be a single good one for most scenarios but as I learn more about it I see the strong focus on SSR which would make hosting more expensive (and possibly more labor-intensive).

In my customized copy I was able to setup node-config for a new directory containing only client-side configs for different tiers. However it causes some conflicts and confusion with your original concept if SSR is being used. Good enough for me if I consciously just use either of them and avoid mixing the two solutions but doesn't look good enough to contribute it to your project. If later other people show interest, then we can talk through and I can send a PR but so far I'm OK with my hack :)

Thanks for this awesome starter btw, you gathered tons of best practices into a nice pack.

**Comment by stungkit** [comment]
> Hey @devzsolt,
> 
> I am not sure if we can integrate this feature with the SPA build. The purpose of the config is that you can transfer information from the server-environment to the application environment and in the SPA build you don't have a server. For that, we would have to come up with a client-side only solution and I don't know how this would fit together with the overall architecture.
> 
> I will add a hint in the docs for every feature if it is available in the SPA build or not. Or maybe get completely rid of the SPA build. I am not sure yet.
> 
> If you have an idea how to integrate it I would love to see a proposal.
> 
> Have a nice day 😊

Hi @devCrossNet, thanks for this amazing repo. From my perspective and use cases, the SPA build is extremely useful. Sometimes users do not need SSR, and prefer to deploy the codebase in production without a server to avoid an unnecessary overhead.

As you suggested, what would help resolve some of the confusion would be a feature list, and possibly detailing some of high level overview of why certain features are included and excluded.

Just my 2 cents, but I advocate on keeping the SPA build :)

**Comment by devCrossNet** [comment]
@stungkit thanks. that’s valuable input. I will create docs dedicated to the SPA build 👍
