### ISSUE TITLE
Problems trying out the 'example guard'

### ISSUE THREAD

**Issue by boredland** [devCrossNet/vue-starter#307]
**Describe the bug**
I want to implement authentication with passportjs. On my way I was trying to understand how the 'beforeEach' works and how I could leverage it. So far, I don't get it.

**To Reproduce**
1. In `src/app/router.ts` i did set ìsAuthenticated` to true:
```
...
// example guard
// TODO remove or adjust in production code
router.beforeEach((to: Route, from: Route, next: any) => {
  if (to.matched.some((record: RouteRecord) => record.meta.requiresAuth)) {
    // this route requires auth, check if logged in if not, redirect to login page.
    const isAuthenticated = true; // TODO implement real auth check
    if (!isAuthenticated) {
      return next({ path: '/login', query: { redirect: to.fullPath } });
    } else {
      return next();
    }
  } else {
    return next();
  }
});
...
```
2. In `src/app/app/routes.ts`
```
...
  // will redirect to `/login` (implemented in `src/app/router`)
  {
    path:      '/counter',
    meta:      { requiresAuth: true },
  }
...
```
3. go to localhost:3000/counter

**Result**
I receive the following error on the console:
```
error: error during rendering: /counter; error: {"stack":"TypeError: Cannot read property 'prefetch' of undefined\n    at Promise.all.matchedComponents.map (webpack-internal:///./src/server/isomorphic.ts:70:31)\n    at Array.map (<anonymous>)\n    at router.onReady (webpack-internal:///./src/server/isomorphic.ts:69:40)\n    at AbstractHistory.onReady (/home/jonass/IdeaProjects/testsoltions-homebase/node_modules/vue-router/dist/vue-router.common.js:1859:5)\n    at VueRouter.onReady (/home/jonass/IdeaProjects/testsoltions-homebase/node_modules/vue-router/dist/vue-router.common.js:2528:16)\n    at Promise (webpack-internal:///./src/server/isomorphic.ts:59:14)\n    at new Promise (<anonymous>)\n    at __webpack_exports__.default (webpack-internal:///./src/server/isomorphic.ts:52:12)\n    at /home/jonass/IdeaProjects/testsoltions-homebase/node_modules/vue-server-renderer/build.js:8386:43\n    at new Promise (<anonymous>)","message":"Cannot read property 'prefetch' of undefined"}
```

**Expected behavior**
I would have expected the counter page to show up.

I'm sure I misunderstood sth fundamental on how authorization should work in this context, and though would be very happy about your support.

**Comment by devCrossNet** [comment]
I will try to help you tomorrow. It’s already late in my timezone 👍

**Comment by boredland** [comment]
That would be so nice!

**Comment by devCrossNet** [comment]
I am at a conference today and tomorrow is it ok if we have a quick chat on the weekend? otherwise, I'll try to find some time today

**Comment by devCrossNet** [comment]
@boredland so I checked out a fresh version of the master branch and added `meta: { requiresAuth: true },` to the route in `./src/app/counter/routes.ts`. When I go to `http://localhost:3000/counter` it redirects me to `http://localhost:3000/login?redirect=%2Fcounter` which is what I expect from the code because I am not authenticated. If I now set `const isAuthenticated = true; // TODO implement real auth check` to true it doesn't redirect, which is correct.

So I don't see a problem so far and I didn't get any errors.

**Comment by boredland** [comment]
Hi! Thank you for looking into this. My problem isn't to get it to redirect, but to render.
In my example you would expect it to render `/counter` or am I completely wrong?

**Comment by devCrossNet** [comment]
@boredland that's correct and it worked yesterday in my case

> If I now set const isAuthenticated = true; // TODO implement real auth check to true it doesn't redirect, which is correct.

do you have a repo that I can check out? Maybe there is another change you did which causes the trouble. 

Would it help you if I reproduce the scenario from yesterday and push it to another branch in this repo that you can check it out?

**Comment by boredland** [comment]
That makes me suspicius. I'll try it myself with a fork for this repo and if it still doesn't work, I'll share the repo with you. Thanks for the hint!

**Comment by devCrossNet** [comment]
@boredland I will have look at it later today 👍

**Comment by boredland** [comment]
Hi! Did you have the time to look into that?

**Comment by devCrossNet** [comment]
@boredland I am super sorry. we have crunch time this week to finish up stuff at work. I promise you to have a closer look tomorrow. It would be nice if you could join the slack channel. it would make it much easier for me to help you. Let me know when you have time for a chat 👍

**Comment by devCrossNet** [comment]
@boredland I left a comment on your repo.

**Comment by boredland** [comment]
Thank you so much!
