### ISSUE TITLE
discussion: new name

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#316]
Let's think about rebranding the vue-starter for version 3

**Comment by devCrossNet** [comment]
- re.vue
- vueable

**Comment by amenadiel** [comment]
VueLerplate

**Comment by devCrossNet** [comment]
Vuesion (Fusion)

**Comment by devCrossNet** [comment]
Vuerious (Furious)

**Comment by devCrossNet** [comment]
@mk42 `Vueture` is amazing 💯

**Comment by devCrossNet** [comment]
@mk42 already taken: https://github.com/vueture

**Comment by mk42** [comment]
i just fired it out brainless xD...

**Comment by mk42** [comment]
...vueyork, vueport, vuethings, vuedelic, vueglasses, vuehood, vuepilot, jetvue, nahisvue.. k i thing thats it for a while ^^

**Comment by devCrossNet** [comment]
I reserved https://github.com/vuesion

**Comment by devCrossNet** [comment]
after getting feedback from several people from different backgrounds I decided that `vuesion` is a really cool brand name and we will transition to the new organization step by step in the next couple of weeks
