### ISSUE TITLE
Can't use webfonts with webpack

### ISSUE THREAD

**Issue by ayZagen** [devCrossNet/vue-starter#320]
**Describe the bug**
I am trying to use vuetify with the mdi iconfont. When I import css which contains webfont, application cannot resolve font file and prints the warning 
`unsupported route: /materialdesignicons-webfont.woff2?d1bdfb3838e2f78edf1ede85f56eabc9; error: {\"code\":404}`
infinitely until OOM. It works sometimes but most of the times it fails.

I re-checked vue-starter's doc and vuetify's. Didn't miss anything. 

**To Reproduce**
1) yarn add `@mdi/font`
2) Go to App.vue 
3) paste in style block
`  @import "../../../../node_modules/@mdi/font/css/materialdesignicons.min.css";`
4) restart the app 

EDIT: Also sometimes I got the infinite warn log and this raises up even without webfonts :
`warn: unsupported route: /client/785c8cdd333e6e8a782e.hot-update.json; error: {"code":404}`

**Comment by devCrossNet** [comment]
@ayZagen sorry I missed to reply you.

did you follow the tutorial in the docs?

the second issue sometimes occurs if you restart the dev server and the client tries to get the HMR script, reloading the page solves this problem, so don't worry about it 😊

**Comment by ayZagen** [comment]
@devCrossNet yeah I followed the tutorial. Application works flawlessly except this error. Refreshing page doesn't work out every time. When this error occurs I need to restart the application itself.

**Comment by devCrossNet** [comment]
ok, I will try to reproduce it and hopefully, I can help you 👍

**Comment by devCrossNet** [comment]
@ayZagen I finally had some time to tackle this issue. In the latest version of the vue-starter it works in the way you describe it. I was able to do exactly what you describe without getting an error.

**Comment by ayZagen** [comment]
@devCrossNet I will look into it when I got spare time. Closing the issue for now. Thanks for keeping your support up!
