### ISSUE TITLE
How can I use elementui in vue-starter?

### ISSUE THREAD

**Issue by phoenixtk** [devCrossNet/vue-starter#324]
**Is your feature request related to a problem? Please describe.**
When I import css, request [testurl](http://localhost:3000/admin/stelementui)
![image](https://user-images.githubusercontent.com/20085025/51224845-c8fd5800-1982-11e9-8c76-c834322862a1.png)
code: https://github.com/phoenixtk/vue-starter.git

**Describe the solution you'd like**
vue-starter fit elementui

**Describe alternatives you've considered**
localation elementui?

**Additional context**
thanks for reading!

**Comment by devCrossNet** [comment]
Hey @phoenixtk , did you have a look at this documentation: https://vue-starter.herokuapp.com/docs/guide/third-party.html ?

Maybe that helps you already.

**Comment by phoenixtk** [comment]
> Hey @phoenixtk , did you have a look at this documentation: https://vue-starter.herokuapp.com/docs/guide/third-party.html ?
> 
> Maybe that helps you already.

thank you very much！

**Comment by devCrossNet** [comment]
@phoenixtk did it help, can I close this issue?

**Comment by phoenixtk** [comment]
It works.Great help,thanks a lot!
