### ISSUE TITLE
spawn ENOENT errors when using vue-starter-service and Windows 10

### ISSUE THREAD

**Issue by Sydtrack** [devCrossNet/vue-starter#331]
**Describe the bug**
When trying to create a new project (via npx create) or run npm (e.g. npm run dev) commands using Windows 10, the spawn command inside vue-starter-service is throwing ENOENT errors.

> C:\Users\me\Development\Testing\intranet-frontend>npm run dev
> vue-starter@2.0.1 dev C:\Users\me\Development\Testing\intranet-frontend
> vue-starter-service dev
> Error: spawn rimraf ENOENT

**To Reproduce**
1. Using Windows 10, Run 'npx vue-starter-server create intranet-frontend'
2. Get error "Error: spawn npm ENOENT"
3. Enter 'intranet-frontend' dir, and run 'npm install'
4. Run 'npm run dev'
5. Get error "Error: spawn rimraf ENOENT"

**Expected behavior**
Expected to install correctly and run development server

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1803 (OS Build 17134.167)
 - Node: v10.15.0
 - NPM: 6.7.0

**Additional context**
It may be related to this: https://github.com/nodejs/node-v0.x-archive/issues/2318
child.spawn is not considering PATHEXT (like .bat, .cmd etc) while spawning processes.

Could node-cross-spawn be a solution?

**Comment by devCrossNet** [comment]
Thanks for reporting. I will try the cross-spawn solution. I will let you know as soon as I released the new version.

**Comment by gjohncock** [comment]
further to the issue above, this might provide more detail about the error
if I run "npm run build" I get the following output...

(node:13956) UnhandledPromiseRejectionWarning: Error: spawn rimraf ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(node:13956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:13956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by devCrossNet** [comment]
I am not in front of a computer today. I will release the cross-spawn version tomorrow and keep you updated. Sorry for the inconvenience

**Comment by devCrossNet** [comment]
I published an update `vue-starter-service@1.0.0-beta.4`. please verify if it works. If everything is fine I'll publish a patch update to the vue-starter repo.

And many thanks for your help! 😊

**Comment by devCrossNet** [comment]
cool, so from what I read everything seems to be fine!?

do me a favour and install the new version like this: `npm install --save vue-starter-service@1.0.0-beta.4`, otherwise it'll not update your package.json.

**Comment by gjohncock** [comment]
ok, have done that.  I appreciate your quick response to the issue.  everything now up and running.  Can see the site at localhost etc.  Well done

**Comment by devCrossNet** [comment]
perfect 👍 

I'll create a patch release and close this issue
