### ISSUE TITLE
Vue-select component in storybook has an undefined error

### ISSUE THREAD

**Issue by farahbrunache** [devCrossNet/vue-starter#333]
**Describe the bug**
When viewing the `vue-select` component in the hosted Storybook link. I see the following error
`Cannot read property 'name' of undefined at constructorToString`

**To Reproduce**
1. Go to https://vue-starter.herokuapp.com/storybook/?selectedKind=2.%20Components%7CSelect&selectedStory=Multi&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel
2. Click on 'Select'
3. See error

**Expected behavior**
The preview of the vue-select component

**Screenshots**
![snip20190129_2](https://user-images.githubusercontent.com/16567092/51943932-c3732980-23e8-11e9-8cea-52ab71c6a023.png)

**Desktop (please complete the following information):**
 - Device: MacBook Pro
 - Browser Chrome
 - Version: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by devCrossNet** [comment]
Thanks for reporting 👍

**Comment by MohitTilwani15** [comment]
@devCrossNet Passing type property to autocomplete prop in vueSelect would fix the issue.

**Comment by devCrossNet** [comment]
Thank you very much! I will check it tomorrow 👍

**Comment by devCrossNet** [comment]
@MohitTilwani15 that worked perfectly!

```    
    autocomplete: {
      type: String,
      default: 'off',
    },```

@farahbrunache this will fix the issue 👍
