### ISSUE TITLE
Hot reloading vue-starter in Vagrant

### ISSUE THREAD

**Issue by davidrichied** [devCrossNet/vue-starter#334]
Hi,
Hot reloading doesn't seem to work when using vue-starter in vagrant. I found a similar issue that was solved by enabling webpack polling ([https://github.com/vuejs-templates/webpack/issues/432](https://github.com/vuejs-templates/webpack/issues/432)), but I'm not sure where I would activate webpack polling. I've run into this issue a lot, and it's usually solved by using a watch-poll option, or I think using nodemon -L once worked as well. Your help is appreciated. Thank you.

**Comment by devCrossNet** [comment]
Hey @davidrichied,

I don't use vagrant and I don't know about the implications. If it's something related to webpack you should check out the following files, maybe you can tweak the config in a way that it works.

https://github.com/devCrossNet/vue-starter/blob/master/src/server/index.ts#L13

https://github.com/devCrossNet/vue-starter-packages/blob/master/packages/vue-starter-service/src/webpack/config/base-server.ts#L14

https://github.com/devCrossNet/vue-starter-packages/blob/master/packages/vue-starter-service/src/webpack/config/server.ts#L25

you can modify the config in this file: https://github.com/devCrossNet/vue-starter/blob/master/.vue-starter/webpack.config.js

```
if (target === 'server') {
  ...
}
```
Let me know how it works out.

**Comment by devCrossNet** [comment]
Hey, can you tell me a little bit more about the problem you try to solve? The dockerfile is an optimized production image that takes as less space as possible in the registry. It’s not linked to the local filesystem and doesn’t contain any source files.

**Comment by davidrichied** [comment]
Found the solution. I made a pull request to devCrossNet/vue-starter-packages
 with the changes that I made, so that you can see what I did. Below is an explanation of what I found.

I noticed that vue-starter-service uses webpack-dev-middleware (but not webpack-dev-server), but [you can include webpack options](https://github.com/webpack/webpack-dev-middleware#watchoptions) when using it.

I found the right options to add to webpack-dev-middleware, and, now, when I save a file (Counter.vue, for example), webpack successfully updates the file, and I can see the changes in the browser.
I added watchOptions to [vue-starter-service/src/webpack/dev/server.ts#L44](https://github.com/devCrossNet/vue-starter-packages/blob/23b4cdf806246b979da4345360c11bf1d0b78314/packages/vue-starter-service/src/webpack/dev/server.ts#L44)
Now, when I save a file in the vue-starter project that I set up in Vagrant, the changes recompile, and I can see the changes in the browser.

I found another article that might explain why it doesn't work by default, but adding watchOptions did it for me. Here's [the article on Vagrant](https://webpack.js.org/guides/development-vagrant/#running-the-server) with another possible solution. It says "We then tackled a common problem that VirtualBox doesn't send out filesystem events, causing the server to not reload on file changes."

**Comment by davidrichied** [comment]
@devCrossNet, I'll let you close this issue when you feel like it's ready to be closed. I don't think editing a file in node_modules (that can be overwritten) is a very good solution, but it's working, for now. Thanks, again.

**Comment by devCrossNet** [comment]
you can replace it now with the new version of `vue-starter-service@1.0.0-beta.7`. If everything works as expected I'll close this issue.
