### ISSUE TITLE
prettier errors

### ISSUE THREAD

**Issue by minzojian** [devCrossNet/vue-starter#335]
when run dev task,got message like this
![image](https://user-images.githubusercontent.com/361781/52041709-29d98280-2576-11e9-939a-546043ca0583.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Version 2.0.2

**Comment by devCrossNet** [comment]
hey @minzojian,

is this after a fresh checkout or did you change this file?

I would suggest to run `npm run prettier` to fix the issues and then run dev again, just to unblock you for now.

**Comment by devCrossNet** [comment]
can I close this @minzojian ?
