### ISSUE TITLE
Dev build failing to complete

### ISSUE THREAD

**Issue by JoeEarly** [devCrossNet/vue-starter#341]
Clone from the repo, performed npm install and then npm run dev which result in a build error. 

**To Reproduce**
1. Clone repo
2. npm install
3. npm run dev

![image](https://user-images.githubusercontent.com/5208459/52305332-ce036500-298c-11e9-988c-145ff35a3532.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - node: 10.13.0

**Comment by devCrossNet** [comment]
@JoeEarly I tried to reproduce it locally, but everything works fine for me.

**Comment by JoeEarly** [comment]
Very strange indeed as I tried it on a clean setup and got the same thing. 

May O ask what platform you are on?

**Comment by devCrossNet** [comment]
I am on OSX. I'll try to reproduce it with a windows vm if I have some time.

**Comment by JoeEarly** [comment]
Ohh it gets worse for some reason....Ill try a different machine later also 

![image](https://user-images.githubusercontent.com/5208459/52591652-5de95900-2e3c-11e9-8a93-07b170362bf3.png)

**Comment by JoeEarly** [comment]
I "think" it my be a permission issue on windows. 

I usually keep all my projects in C:/Source/... however when I moved this to the Documents folder it fired up nicely. 

![image](https://user-images.githubusercontent.com/5208459/52661608-55efee80-2efa-11e9-9e6c-16e37d3b2bc7.png)

**Comment by devCrossNet** [comment]
Nice 1, does that mean we can close this issue?

**Comment by JoeEarly** [comment]
Does indeed

**Comment by devCrossNet** [comment]
Cool! Have (finally) fun with the vue-starter 👍
