### ISSUE TITLE
Failed at the vue-starter@2.0.2 build script. help wanted

### ISSUE THREAD

**Issue by lmnzr** [devCrossNet/vue-starter#349]
I tried npm run dev immedietly after npm install. Then I stumble into this error.

This Is the Log I got 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-starter@2.0.2 prebuild: vue-starter@2.0.2
6 info lifecycle vue-starter@2.0.2 build: vue-starter@2.0.2
7 verbose lifecycle vue-starter@2.0.2 build: unsafe-perm in lifecycle true
8 verbose lifecycle vue-starter@2.0.2 build: PATH: 
9 verbose lifecycle vue-starter@2.0.2 build: CWD: D:\LearnBox\vue\vue-starter
10 silly lifecycle vue-starter@2.0.2 build: Args: [ '/d /s /c', 'vue-starter-service build' ]
11 silly lifecycle vue-starter@2.0.2 build: Returned: code: 2  signal: null
12 info lifecycle vue-starter@2.0.2 build: Failed to exec build script
13 verbose stack Error: vue-starter@2.0.2 build: `vue-starter-service build`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid vue-starter@2.0.2
15 verbose cwd D:\LearnBox\vue\vue-starter
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error vue-starter@2.0.2 build: `vue-starter-service build`
22 error Exit status 2
23 error Failed at the vue-starter@2.0.2 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

can you suggest a way to fix it ?

Thank you

**Comment by devCrossNet** [comment]
Hey, I don’t have a Windows System to reproduce it. Maybe this thread helps: https://github.com/devCrossNet/vue-starter/issues/341

**Comment by lmnzr** [comment]
Thank for the Reply. I have tried it. Doesn't seem to solve my problem. Probably related to windows configuration or the npm installation.

**Comment by lmnzr** [comment]
Ok I Managed To solve It. The Problem is Related to this
https://github.com/ForbesLindesay/spawn-sync/issues/19

Thank you for the support.

**Comment by devCrossNet** [comment]
Good to know. Thank you very much. I will update the dependency asap 👍
