### ISSUE TITLE
Changing locale works only once

### ISSUE THREAD

**Issue by rgrosjean** [devCrossNet/vue-starter#353]
**Describe the bug**
When updating the value of app.locale in the store, the UI react only once and does not update the texts any more.

**To Reproduce**
1. Go to (https://vue-starter.herokuapp.com)
2. Open the left panel and change the language (e.g. German)
3. Set the language to the previous one
4. Try to set the language again to German, the text does not change anymore

**Expected behavior**
The texts on the page should always change according the value set in the store of Vuex.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39985706/53421389-d8d67600-39dd-11e9-9fcc-a2cd57aa0159.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browsers:  lastest versions of Chromium and Firefox
 - Version: 2.1.0

**Comment by devCrossNet** [comment]
nice catch @rgrosjean. I think it's only an issue in production because of the service-worker. I will investigate asap!

**Comment by rgrosjean** [comment]
hi @devCrossNet , I have the same issue when running in dev mode (that's how I found it). I thought first I broke something

**Comment by devCrossNet** [comment]
Good to know. I hope it will be easy to fix. I will spend some time over the weekend 👍

**Comment by rgrosjean** [comment]
I could try to fix it too... just don't know where I should start :smile:  but thanks

**Comment by devCrossNet** [comment]
I would start here: https://github.com/devCrossNet/vue-starter/blob/master/src/app/app/App/App.vue#L157

and then observe what happens in `loadLocaleAsync` and `changeLocale`.

**Comment by devCrossNet** [comment]
@rgrosjean here is the fix: https://github.com/devCrossNet/vue-starter/pull/356
