### ISSUE TITLE
update storybook

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#369]
https://medium.com/storybookjs/storybook-5-migration-guide-d804b38c739d

**Comment by MohitTilwani15** [comment]
@devCrossNet How do you manage the local development of vuesion, so that you can quickly check the changes in vue-starter, before committing the changes in vuesion?

**Comment by devCrossNet** [comment]
hey @MohitTilwani15,
I use a local npm registry where I release my packages and install them from there in the vue-starter. But only if I need to update dependencies. 

For normal improvements in the CLI I use npm link

**Comment by devCrossNet** [comment]
this is the package: https://github.com/verdaccio/verdaccio

and then I set the new registry in the projects `.npmrc`

**Comment by MohitTilwani15** [comment]
@devCrossNet okay superb module verdaccio. Also I have updated the storybook to version 5. I have to check few things before committing it. Looks great as of now. Will raise a PR latest by tomorrow. Cheers!

**Comment by devCrossNet** [comment]
Thank you very much 🙂

**Comment by MohitTilwani15** [comment]
@devCrossNet I think you need to give me access to push in vuesion, as I cannot even push in my local branch

**Comment by devCrossNet** [comment]
You should fork it and create a PR from your fork to the origin repo. We can talk about being a maintainer after a couple of PRs if you want, ok?
