### ISSUE TITLE
component: lazy loading image

### ISSUE THREAD

**Issue by devCrossNet** [devCrossNet/vue-starter#382]
use intersection observer to lazy load images, as `img` and background image

**Comment by MohitTilwani15** [comment]
@devCrossNet If can take over this task if its okay for you. I was thinking to make a ```VueImage``` component which would lay load the image using Intersection Observer and then instead of using ```img``` tag, we can use ```VueImage``` component.

**Comment by devCrossNet** [comment]
that's exactly my goal. here is already the working code. it has to separated out into a component: https://github.com/devCrossNet/vue-starter/blob/vuesion/src/app/home/components/HomeSection/HomeSection.vue#L47

Important is to include a fallback for older browsers and to also gove the possibility to render is as a DIV with the image URL as the background image (a use-case I need sometimes).

I would start tomorrow I guess, because I am on vacation 😊

**Comment by MohitTilwani15** [comment]
ohh okay. Cool. Then you can take care of it (y)

**Comment by MohitTilwani15** [comment]
But one small thing in your example, I can see that you're making this.observer = null on component beforeDestroy lifecycle, which means even when image is loaded, the  Intersection Observer is still watching for intersection. So I would suggest after `this.$refs.image.style.backgroundImage = url(${this.image})` you should call `this.observer.disconnect()` so that observer would stop watching

**Comment by devCrossNet** [comment]
I will send you the PR when it's ready so you can review it 👍

**Comment by devCrossNet** [comment]
@MohitTilwani15 I just saw you don't have 2FA enabled. would be a big security win for you if you enable it. should not be so complicated to set it up

**Comment by MohitTilwani15** [comment]
> @MohitTilwani15 I just saw you don't have 2FA enabled. would be a big security win for you if you enable it. should not be so complicated to set it up

Done. Thanks 👍

**Comment by devCrossNet** [comment]
@MohitTilwani15 here is the PR https://github.com/devCrossNet/vue-starter/pull/386. If you think it's alright, plz comment with `LGTM` or something similar.
