### ISSUE TITLE
Best practice to have key attribute with v-for and avoid v-if with v-for

### ISSUE THREAD

**Issue by MohitTilwani15** [devCrossNet/vue-starter#387]
**Describe the bug**
In some components v-for is used with v-if which as per Vue documentation is not a good practice. Also key is missing in some components.
[https://vuejs.org/v2/guide/list.html#v-for-with-v-if](https://vuejs.org/v2/guide/list.html#v-for-with-v-if)

**Expected behavior**
Best practice should be followed as per documentation.

Components that needs to be fixed:

1. VueBreadcumb
2. VueCalendar
3.  VueDataTable
4. VueDataTableHeader
5. VueDonutChart
6. VueSelect

**Comment by devCrossNet** [comment]
will be in the next release
