### ISSUE TITLE
add storybook

### ISSUE THREAD

**Issue by sky790312** [devCrossNet/vue-starter#41]
any idea to use storybook?

**Comment by devCrossNet** [comment]
Hey @sky790312, I never needed storybook. Can you give me a little bit more information about the benefits of storybook?

**Comment by sky790312** [comment]
It's like UI component guide. Showing what the component can do.
Or it can show the effect which the website has used.

airbnb's datepicker sample:
http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

Support vue too. You can check on my project. :)
https://github.com/sky790312/new-website

**Comment by devCrossNet** [comment]
does it work with Typescript too?

**Comment by sky790312** [comment]
I haven't try, but I believe it's solved now.
Check this issue:
https://github.com/storybooks/storybook/issues/2792
