### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by kslstn** [devCrossNet/vue-starter#7]
I'd like to try this, but don't know how. I guessed I can install it with _npm install vue-starter_. After that I tried _npm vue-starter_ and got  _Did you mean this? restart_ as a response. I would very much appreciate a fool proof Readme.

That is, in case this project does what I hope: create boilerplates for Vue applications!

**Comment by devCrossNet** [comment]
Hey Koos,

it is not an NPM package, so you have to download or `git clone` it to a folder of your choice.

If you already have node.js and npm installed you just have to `cd` into the project folder and follow the steps from the `README.md` (basically `npm i && npm run dev`)

I'll improve the `README.md` asap. Or you could create a pull request if you know how to better onboard beginners.
