### ISSUE TITLE
Modify regex to support plurals in i18n (proposed solution)

### ISSUE THREAD

**Issue by cureau** [devCrossNet/vue-starter#83]
Hi! Not exactly sure how to do PR right now. Feel to close if this is unwelcome. 

But wouldn't you want to support $tc('') in the i18n extractor (for plurals):

This regex would allow for it:

`\$tc?\([\r,\n, ,\S,"]*?\)`

(also adding double quotes for flexibility around `$t("double-quoted-keys")`

And then you can add magic comments with pluralized forms. E.g, 

`$tc('org', 2 /* Organization | Organizations */)`

**Comment by devCrossNet** [comment]
Hey Kyle!
every PR is very welcome. If this is not clear it would be good if can provide some tips or create a PR to communicate that better. Here are the guidelines: https://github.com/devCrossNet/vue-starter/blob/master/.github/CONTRIBUTING.md
 
The reason why I just support the `$t` function by now is pretty simple -  I didn't need other functions. I implement use case by use case.

I would really appreciate a PR.

**Comment by devCrossNet** [comment]
no one else did request this feature so I close this issue and focus on other topics.
